import {useEffect, useState} from "react";

export const useDocumentaries = () => {
    const [documentaries, setDocumentaries] = useState([]);

    useEffect(() => {
        setTimeout(() => {
            setDocumentaries ([
                {
                    id: "0",
                    titulo: "Taylor Swift: The Eras Tour",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BNmQxZjdlMzMtMDUxMC00OWYwLTk1OWQtNjI2YTlkY2I1MjllXkEyXkFqcGdeQXVyMTY3ODkyNDkz._V1_.jpg',
                    sipnosis: "Disfruta del impresionante concierto Eras Tour, interpretado por la única e inigualable Taylor Swift.",
                    duracion: "2h 49min",
                    genero: "Música",
                    direccion: "Sam Wrench",
                    guion: "Taylor Swift",
                    puntuacion: 8.2,
                    url: 'https://www.youtube.com/watch?v=pUG-509ZhDE'
                },
                {
                    id: "1",
                    titulo: "Renaissance: A Film by Beyoncé",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BNDBhODM5MjMtNTdkYy00ZTIxLWEwNWYtZTA1MDBkYjAzZjJhXkEyXkFqcGdeQXVyMTY0Njc2MTUx._V1_.jpg',
                    sipnosis: "Beyoncé en plena actuación de su gira mundial Renaissance, que bate récords, y el cerebro creativo que hay detrás.",
                    duracion: "2h 49min",
                    genero: "Música",
                    direccion: "Ed Burke",
                    guion: "Beyoncé",
                    puntuacion: 8.7,
                    url: 'https://youtube.com/watch?v=ByV3XWl8zWU'
                },
                {
                    id: "2",
                    titulo: "The Mission",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BODc2NzcyMjYtZDE0Ny00Y2M0LThhYWMtZDJhMGJhOGViMDU5XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_.jpg',
                    sipnosis: "El misionero estadounidense John Chau, de 26 años, fue asesinado cuando intentaba entrar en contacto con un grupo indígena frente a las costas de la India, una de las últimas comunidades del planeta que aún viven aisladas.",
                    duracion: "1h 43min",
                    genero: "Documental",
                    direccion: "Amanda McBaine",
                    guion: "Jesse Moss",
                    puntuacion: 6.4,
                    url: 'https://www.youtube.com/watch?v=afg1V6WOM80'
                },
                {
                    id: "3",
                    titulo: "American Symphony",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BZmRiYjQ2MDItN2I5OC00Yjk1LTllYTEtMDZlZDAyZjgxZDVmXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_.jpg',
                    sipnosis: "Explora un año en la vida del músico Jon Batiste.",
                    duracion: "1h 44min",
                    genero: "Biografía",
                    direccion: "Matthew Heineman",
                    guion: "Jon Batiste",
                    puntuacion: 7.3,
                    url: 'https://www.youtube.com/watch?v=r7HGiv92g5I'
                },
                {
                    id: "4",
                    titulo: "Smoke Sauna Sisterhood",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BMGUxNDA2OTgtYTlkZi00OWVhLTgzZTEtMDMwMzNhZDk1OGUxXkEyXkFqcGdeQXVyOTM5NzYzNTU@._V1_.jpg',
                    sipnosis: "En la oscuridad de una sauna de humo, las mujeres comparten sus secretos más íntimos y sus experiencias más íntimas, lavando la vergüenza atrapada en sus cuerpos y recuperando su fuerza a través de un sentimiento de comunión.",
                    duracion: "1h 29min",
                    genero: "Documental",
                    direccion: "Anna Hints",
                    guion: "Anna Hints",
                    puntuacion: 7.7,
                    url: 'https://www.youtube.com/watch?v=BzOe9SYiwtY'
                },
                {
                    id: "5",
                    titulo: "Árboles y otros enredos",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BMDhhMWUyN2YtMWJiYS00OTkxLTkwNGEtMDBhZjY3NTkxMTFiXkEyXkFqcGdeQXVyMTE4MTEyMzE2._V1_.jpg',
                    sipnosis: "Irene Taylor elabora una meditación poética sobre la naturaleza, la mortalidad y el paso del tiempo en su exploración de nuestro nexo simbiótico con los árboles.",
                    duracion: "3h 26min",
                    genero: "Crimen",
                    direccion: "Martin Scorsese",
                    guion: "Eric Roth",
                    puntuacion: 7.8,
                    url: 'https://www.youtube.com/watch?v=HyyWd2XI1EE'
                },
                {
                    id: "6",
                    titulo: "Leave the World Behind",
                    year: 2014,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BMjI2MTg2MDA1NV5BMl5BanBnXkFtZTgwOTMzMjQyMTE@._V1_.jpg',
                    sipnosis: "A music documentary following the last tour of the band Swedish House Mafia in 2012/2013, the film tells a story of friendship and huge success.",
                    duracion: "1h 35min",
                    genero: "Música",
                    direccion: "Christian Larson",
                    guion: "Steve Angello",
                    puntuacion: 7.7,
                    url: 'https://www.youtube.com/watch?v=v-kFSLbY9u8'
                },
                {
                    id: "7",
                    titulo: "After Death",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BODA5YmY3NmMtMjExYi00NDY1LTkyODItMDU1NTE1NzY5OTA0XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_.jpg',
                    sipnosis: "Basado en experiencias reales cercanas a la muerte, After Death explora el más allá con la guía de exitosos autores del New York Times, expertos médicos, científicos y supervivientes que arrojan luz sobre lo que espera, al otro lado.",
                    duracion: "1h 48min",
                    genero: "Documental",
                    direccion: "Stephen Gray",
                    guion: "Stephen Gray",
                    puntuacion: 6.2,
                    url: 'https://www.youtube.com/watch?v=1BWh_LjOOlo'
                },
                {
                    id: "8",
                    titulo: "A Disturbance in the Force",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BYzEzZmMwMmEtNTc2OC00NzA4LWEwMzQtZWM2ODQ5ZDc1NTZjXkEyXkFqcGdeQXVyNzkyMDA5MTc@._V1_.jpg',
                    sipnosis: "In 1978, filmmaker George Lucas is persuaded to turn over Star Wars to the world of the '70s variety hour, culminating in El especial navideño de la Guerra de las Galaxias (1978), often cited as one of the worst forms of entertainment of all time.",
                    duracion: "1h 25min",
                    genero: "Historia",
                    direccion: "Jeremy Coon",
                    guion: "Bruce Vilanch",
                    puntuacion: 6.8,
                    url: 'https://www.youtube.com/watch?v=z1DPggJsrRY'
                },
                {
                    id: "9",
                    titulo: "Occupied City",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BZjliOGVjYzQtMjhlYi00MDdhLWJlZmQtNmRkNDkzOTExOTc5XkEyXkFqcGdeQXVyMTM1NjM2ODg1._V1_.jpg',
                    sipnosis: "El pasado choca con el presente en esta excavación de la ocupación nazi de Ámsterdam: desde la II Guerra Mundial hasta los últimos años de pandemia y protestas. Una reflexión provocadora sobre la memoria, el tiempo y lo que está por venir.",
                    duracion: "4h 6min",
                    genero: "Historia",
                    direccion: "Steve McQueen",
                    guion: "Bianca Stigter",
                    puntuacion: 7.0,
                    url: 'https://www.youtube.com/watch?v=qOYrpk-A45s'
                },
                {
                    id: "10",
                    titulo: "The Fall of Minneapolis",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BNzQ0NjhhMjMtY2MxMC00ZDIyLTllN2EtMDgwZGMxYTliOTIyXkEyXkFqcGdeQXVyMTcyOTE0ODMx._V1_.jpg',
                    sipnosis: "A multi-part documentary featuring: body worn camera video of George Floyd's arrest; interviews with officers who served during the riots; key evidence from the autopsy and Derek Chauvin's trial; and the aftermath that followed.",
                    duracion: "1h 42min",
                    genero: "Crimen",
                    direccion: "JC Chaix",
                    guion: "JC Chainx",
                    puntuacion: 8.4,
                    url: 'https://www.youtube.com/watch?v=Cxc7wCEVSa0'
                },
                {
                    id: "11",
                    titulo: "David Holmes: El chico que sobrevivió",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BZjI1MzkyZWQtOGJjNS00ZTMwLTlmNjktZTA5MDIxMGYxZTdkXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_.jpg',
                    sipnosis: "Un documental sobre la madurez de Daniel Radcliffe y su doble David Holmes, cuya estrecha amistad se ve afectada por un accidente que les cambia la vida.",
                    duracion: "1h 27min",
                    genero: "Documental",
                    direccion: "Dan Hartley",
                    guion: "Dan Hartley",
                    puntuacion: 7.8,
                    url: 'https://www.youtube.com/watch?v=1tWi5BiXqCE'
                },
                {
                    id: "12",
                    titulo: "Anselm",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BNWM0ZjQxNDUtYmZlNi00Nzc3LWI5OWYtMmJiN2I5YjQ3OWUwXkEyXkFqcGdeQXVyODA0MjgyNzM@._V1_.jpg',
                    sipnosis: "Anselm Kiefer es uno de los más grandes artistas contemporáneos. Su pasado y su presente difuminan la línea entre el cine y la pintura, ofreciendo así una experiencia cinematográfica única.",
                    duracion: "1h 33min",
                    genero: "Documental",
                    direccion: "Wim Wenders",
                    guion: "Wim Wenders",
                    puntuacion: 7.2,
                    url: 'https://www.youtube.com/watch?v=JYb4wDJKpsQ'
                },
                {
                    id: "13",
                    titulo: "Thriller 40",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BY2E4ZmRkNTctYzI5Yy00M2Q2LTg5N2EtZDZjZmU0MmE4ZDRkXkEyXkFqcGdeQXVyMTM1NjM2ODg1._V1_.jpg',
                    sipnosis: "Sigue la grabación de \"Thriller\", el álbum de Michael Jackson que batió todos los récords.",
                    duracion: "1h 30min",
                    genero: "Música",
                    direccion: "Nelson George",
                    guion: "Nelson George",
                    puntuacion: 8.0,
                    url: 'https://www.youtube.com/watch?v=YLFMLRjp124'
                },
                {
                    id: "14",
                    titulo: "Apolonia, Apolonia",
                    year: 2022,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BYmY4ZDQwYmUtZWU0Ny00Zjk3LWJkNmItNjQ1YWUyMmIzZTYzXkEyXkFqcGdeQXVyMjMxMjIzMTc@._V1_.jpg',
                    sipnosis: "La talentosa Apolonia crece buscando su lugar en el mundo del arte mientras lidia con las agonías y alegrías de la feminidad y las relaciones en un mundo dominado por el patriarcado, el capitalismo y la guerra.",
                    duracion: "1h 56min",
                    genero: "Biografía",
                    direccion: "Lea Glob",
                    guion: "Lea Glob",
                    puntuacion: 7.3,
                    url: 'https://www.youtube.com/watch?v=IARMK6mwhHg'
                },
                {
                    id: "15",
                    titulo: "Ronnie O'Sullivan: The Edge of Everything",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BMGNjMWMwOWItODJhYy00Njg5LTgwMmUtZjgyMWY4MDVjNDFiXkEyXkFqcGdeQXVyMDc5ODIzMw@@._V1_.jpg',
                    sipnosis: "Centrada en comprender la genialidad del jugador, esclarecer su pasado a través de imágenes familiares de archivo y trazar su ascenso a la fama desde su adolescencia y los desafíos mentales que ha superado en su búsqueda de la perfección.",
                    duracion: "1h 53min",
                    genero: "Documental",
                    direccion: "Sam Blair",
                    guion: "Sam Blair",
                    puntuacion: 7.7,
                    url: 'https://www.youtube.com/watch?v=-fufI8Y6h7I'
                },
                {
                    id: "16",
                    titulo: "Sly",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BMTJjNDI2OWYtYmVhZi00NDA4LTliZTQtMThmMWJiYjg2YzcyXkEyXkFqcGdeQXVyNjc5NjEzNA@@._V1_.jpg',
                    sipnosis: "Los casi cincuenta años de carrera de Sylvester Stallone, ha entretenido a millones de personas, se ven en retrospectiva en una visión íntima del actor, guionista, director y productor, en paralelo con la inspiradora historia de su vida.",
                    duracion: "1h 35min",
                    genero: "Biografía",
                    direccion: "Thom Zimny",
                    guion: "Aidin Sayar Sarie",
                    puntuacion: 7.0,
                    url: 'https://www.youtube.com/watch?v=yWdeL2_YND8'
                },
                {
                    id: "17",
                    titulo: "Beyond Utopia",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BMzhlOTQyYTYtYTY5Yy00ZDkxLTkwYTYtMjQzOGE1ODllZjhjXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_.jpg',
                    sipnosis: "La historia de varias familias que intentan escapar de la opresión en Corea del Norte, revelando un mundo que la mayoría de las personas nunca han visto.",
                    duracion: "1h 55min",
                    genero: "Biografía",
                    direccion: "Madeleine Gavin",
                    guion: "Barbara Demick",
                    puntuacion: 7.8,
                    url: 'https://www.youtube.com/watch?v=sVmKew4YYSY'
                },
                {
                    id: "18",
                    titulo: "What Is a Woman?",
                    year: 2022,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BY2JiMWExOTItNWIzYy00NmQ1LThkNGEtMTk5MmM1YmE5NGVmXkEyXkFqcGdeQXVyMTUzMjQxODI1._V1_.jpg',
                    sipnosis: "Es la pregunta que no hay manera de hacer. El documental que no quieren que veas.",
                    duracion: "1h 35min",
                    genero: "Documental",
                    direccion: "Justin Folk",
                    guion: "Justin Folk",
                    puntuacion: 8.2,
                    url: 'https://www.youtube.com/watch?v=42ivIRd9N8E'
                },
                {
                    id: "19",
                    titulo: "Immediate Family",
                    year: 2022,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BNjFhN2EzODEtZWFkMy00NDY4LWJjNmQtNjFiN2FmODVmYzRlXkEyXkFqcGdeQXVyMTA2MDU0NjM5._V1_.jpg',
                    sipnosis: "Documentary follows the work and lives of legendary 1970s session musicians who were featured on some of the most iconic recordings of the era.",
                    duracion: "1h 42min",
                    genero: "Música",
                    direccion: "Denny Tedesco",
                    guion: "Denny Tedesco",
                    puntuacion: 9.4,
                    url: 'https://www.youtube.com/watch?v=mr4OB8r56Oc'
                },
                {
                    id: "20",
                    titulo: "Bye Bye Barry",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BMWQ3YmNjODktNTE4Ny00MDA2LWE0MmMtNjkyYTQyNjY0MGUzXkEyXkFqcGdeQXVyNDc5NDc2Nw@@._V1_.jpgs',
                    sipnosis: "La historia definitiva de la carrera de Barry Sanders en el Salón de la Fama y su extraordinaria decisión de abandonar el fútbol en el mejor momento de su carrera.",
                    duracion: "1h 32min",
                    genero: "Deporte",
                    direccion: "Paul Monusky",
                    guion: "Paul Monusky",
                    puntuacion: 7.9,
                    url: 'https://www.youtube.com/watch?v=kU-zXyOLQNo'
                },
                {
                    id: "21",
                    titulo: "Squaring the Circle: The Story of Hipgnosis",
                    year: 2022,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BMTBmYjBiMWEtMzFlNC00NTcxLTlmZGUtYzY5NTlkYzQzNzZiXkEyXkFqcGdeQXVyNTM0NTU5Mg@@._V1_.jpg',
                    sipnosis: "La historia del estudio de diseño de carátulas de álbumes Hipgnosis, que creó algunas de las portadas de álbumes más icónicas de todos los tiempos.",
                    duracion: "1h 41min",
                    genero: "Documental",
                    direccion: "Anton Corbijn",
                    guion: "Trish D Chetty",
                    puntuacion: 7.7,
                    url: 'https://www.youtube.com/watch?v=-OYQNAk_krQ'
                },
                {
                    id: "22",
                    titulo: "Elijo creer",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BOWI1M2RjM2ItNjRmOS00NjFlLTg0ZTItMTRlNWYxYTI2YzAxXkEyXkFqcGdeQXVyOTE1NDQ5OA@@._V1_.jpg',
                    sipnosis: "Narra el épico título obtenido por la Selección Argentina en el Mundial de Fútbol Qatar 2022 con testimonios de los protagonistas, contados desde la intimidad y en primera persona.",
                    duracion: "1h 42min",
                    genero: "Deporte",
                    direccion: "Gonzalo Arias",
                    guion: "Martín Méndez",
                    puntuacion: 8.2,
                    url: 'https://www.youtube.com/watch?v=-G5cvtQUV14'
                },
                {
                    id: "23",
                    titulo: "La inspiración más profunda",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BN2EzYmM0ODgtNjk0OC00MDVjLWIzYmYtMThjNGQxOTA5ODc3XkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_.jpg',
                    sipnosis: "Unidos por su amor al mismo deporte, una campeona de apnea y un heroico buceador de seguridad están dispuestos a arriesgarlo todo para hacer historia con una proeza.",
                    duracion: "1h 48min",
                    genero: "Aventura",
                    direccion: "Laura McGann",
                    guion: "Laura McGann",
                    puntuacion: 7.7,
                    url: 'https://www.youtube.com/watch?v=kR3OpRU-VA8'
                },
                {
                    id: "24",
                    titulo: "Free Solo",
                    year: 2018,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BMjMwYjcwNWQtNTQ5YS00MzVlLTkxYzMtNDIwZWIxZTE4Zjg2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
                    sipnosis: "Sigue a Alex Honnold mientras se convierte en la primera persona en escalar los 3.000 pies de El Capitán Wall en Yosemite. En solitario, sin cuerdas, ni equipo de seguridad, completó lo que algunos creen es la mayor hazaña en la historia de la escalada en roca.",
                    duracion: "1h 40min",
                    genero: "Aventura",
                    direccion: "Jimmy Chin",
                    guion: "Jimmy Chin",
                    puntuacion: 8.1,
                    url: 'https://www.youtube.com/watch?v=33HLtSzPeRs'
                },
                ]);
            }, 1500);
    }, []);

    return documentaries;
}