import {useEffect, useState} from "react";

export const useMovies = () => {
    const [movies, setMovies] = useState([]);

    useEffect(() => {
        setTimeout(() => {
            setMovies([
                {
                    id: "0",
                    titulo: "Napoleón",
                    year: 2023,
                    imagen: 'https://es.web.img2.acsta.net/r_1920_1080/pictures/23/10/18/15/26/3220184.jpg',
                    sipnosis: "Una perspectiva íntima de los orígenes de Napoleón Bonaparte y su veloz " +
                        "e implacable ascenso al trono, a través del enfoque de su cautivadora e inestable relación con su " +
                        "esposa y único amor verdadero, Josefina.",
                    duracion: "2h 38min",
                    genero: "Aventura",
                    direccion: "Ridley Scott",
                    guion: "David Scarpa",
                    puntuacion: 6.6,
                    url: 'https://www.youtube.com/watch?v=-Wux16EFEL4'
                },
                {
                    id: "1",
                    titulo: "Dejar el mundo atrás",
                    year: 2023,
                    imagen: 'https://cl.buscafs.com/www.tomatazos.com/public/uploads/images/423771/423771_832x1248.jpg',
                    sipnosis: "Drama familiar basado en la próxima novela de Rumaan Alam.",
                    duracion: "2h 18min",
                    genero: "Drama",
                    direccion: "Sam Esmail",
                    guion: "Rumaan Alam",
                    puntuacion: 6.5,
                    url: 'https://www.youtube.com/watch?v=9fsQyW1fWXE'
                },
                {
                    id: "2",
                    titulo: "Animal",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BNGViM2M4NmUtMmNkNy00MTQ5LTk5MDYtNmNhODAzODkwOTJlXkEyXkFqcGdeQXVyMTY1NDY4NTIw._V1_FMjpg_UX1078_.jpg',
                    sipnosis: "A menudo ausente por motivos de trabajo, el padre es incapaz de comprender la intensidad del amor de su hijo. Irónicamente, este ferviente amor y admiración por su padre y su familia crea un conflicto entre padre e hijo.",
                    duracion: "3h 24min",
                    genero: "Acción",
                    direccion: "Sandeep Reddy Vanga",
                    guion: "Suresh Bandaru",
                    puntuacion: 6.9,
                    url: 'https://www.imdb.com/video/vi3071461145/?playlistId=tt13751694&ref_=tt_ov_vi'
                },
                {
                    id: "3",
                    titulo: "Wonka",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BNDM4NTk0NjktZDJhMi00MmFmLTliMzEtN2RkZDY2OTNiMDgzXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg',
                    sipnosis: "La historia se centrará específicamente en un joven Willy Wonka y en cómo conoció a los Oompa-Loompas en una de sus primeras aventuras.",
                    duracion: "1h 56min",
                    genero: "Aventura",
                    direccion: "Paul King",
                    guion: "Simon Farnaby",
                    puntuacion: 7.4,
                    url: 'https://www.youtube.com/watch?v=EJoom2F-7nI'
                },
                {
                    id: "4",
                    titulo: "Pobres criaturas",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BNzIyYjY2OTMtNjdjNC00ZjQwLTk1OTMtZDljMWNhODM2NzE2XkEyXkFqcGdeQXVyODY5Njk4Njc@._V1_FMjpg_UX1080_.jpg',
                    sipnosis: "La increíble historia sobre la fantástica evolución de Bella Baxter, una joven devuelta a la vida por el brillante y poco ortodoxo científico el doctor Godwin Baxter.",
                    duracion: "2h 38min",
                    genero: "Comedia",
                    direccion: "Yorgos Lanthimost",
                    guion: "Tony McNamara",
                    puntuacion: 8.5,
                    url: 'https://www.youtube.com/watch?v=SsEojV8hZ9I'
                },
                {
                    id: "5",
                    titulo: "Los asesinos de la luna",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BYTMyNWU5M2UtYjlhNi00NGRjLWEwMDQtNWFhMjI0OTE2YTQwXkEyXkFqcGdeQXVyMzUxNTM4ODc@._V1_FMjpg_UX595_.jpg',
                    sipnosis: "En la década de 1920 en los Estados Unidos, miembros de la tribu Osage son asesinados bajo misteriosas circunstancias, provocando una importante investigación del FBI involucrando a J. Edgar Hoover.",
                    duracion: "3h 26min",
                    genero: "Crimen",
                    direccion: "Martin Scorsese",
                    guion: "Eric Roth",
                    puntuacion: 7.8,
                    url: 'https://www.youtube.com/watch?v=HyyWd2XI1EE'
                },
                {
                    id: "6",
                    titulo: "Godzilla Minus One",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BYTZkNWQyMDEtMmRhNi00Nzc5LWFhNjQtMWRiOTllYmEzOWE5XkEyXkFqcGdeQXVyMTMwNzYxMTUx._V1_.jpg',
                    sipnosis: "Japón, desolado tras el fin de la Segunda Guerra Mundial, entra en crisis tras la apparencia de un monstruo creado por la bomba atómica.",
                    duracion: "2h 4min",
                    genero: "Acción",
                    direccion: "Takashi Yamazaki",
                    guion: "Takashi Yamazaki",
                    puntuacion: 8.4,
                    url: 'https://www.youtube.com/watch?v=CWWdIJiDfe4'
                },
                {
                    id: "7",
                    titulo: "Secretos de un escándalo",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BMjkyMjI5NmQtM2RkNS00YTU4LTlhOGQtMzg3NGExMzU2OTkzXkEyXkFqcGdeQXVyMTM1NjM2ODg1._V1_FMjpg_UX550_.jpg',
                    sipnosis: "Veinte años después de que su notorio romance de tabloide se apoderara de la nación, una pareja casada se enfrenta a la presión cuando una actriz llega a hacer una investigación para una película sobre su pasado.",
                    duracion: "1h 57min",
                    genero: "Comedia",
                    direccion: "Todd Haynes",
                    guion: "Todd Haynes",
                    puntuacion: 7.0,
                    url: 'https://www.youtube.com/watch?v=PScqyfPFjoQ'
                },
                {
                    id: "8",
                    titulo: "Los juegos del hambre: Balada de pájaros cantores y serpientes",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BZTJkZTlmZDItMjIzYS00YjlmLWExMGQtMjFmNWI4YTg5NzU0XkEyXkFqcGdeQXVyNDc0MDkxNTA@._V1_FMjpg_UY2807_.jpg',
                    sipnosis: "Coriolanus Snow ejerce de mentor y desarrolla sentimientos hacia la tributo femenina del Distrito 12 durante los X Juegos del Hambre.",
                    duracion: "2h 37min",
                    genero: "Acción",
                    direccion: "Francis Lawrence",
                    guion: "Michael Lesslie",
                    puntuacion: 7.1,
                    url: 'https://www.youtube.com/watch?v=Lrsanb7sNME'
                },
                {
                    id: "9",
                    titulo: "El chico y la garza",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BZjZkNThjNTMtOGU0Ni00ZDliLThmNGUtZmMxNWQ3YzAxZTQ1XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UY2194_.jpg',
                    sipnosis: "Sigue el desarrollo psicológico de un adolescente a través de las interacciones con sus amigos y su tío. Se basa en el libro del mismo nombre de 1937 de Genzaburo Yoshino.",
                    duracion: "2h 4min",
                    genero: "Animación",
                    direccion: "Hayao Miyazaki",
                    guion: "Hayao Miyazaki",
                    puntuacion: 7.7,
                    url: 'https://www.youtube.com/watch?v=oDIbOWgADr8'
                },
                {
                    id: "10",
                    titulo: "Love Actually",
                    year: 2003,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BYjRiZjhlY2MtZmJlNC00OTM5LWJmMjItMzYzNjE5MDE5Y2Y5XkEyXkFqcGdeQXVyMTgxOTIzNzk@._V1_FMjpg_UX758_.jpg',
                    sipnosis: "Las vidas de ocho parejas muy diferentes que se ocupan de sus vidas amorosas durante un mes frenético antes de Navidad en Londres.",
                    duracion: "2h 15min",
                    genero: "Comedia",
                    direccion: "Richard Curtis",
                    guion: "Richard Curtis",
                    puntuacion: 7.6,
                    url: 'https://www.youtube.com/watch?v=sXGrMc8LphA'
                },
                {
                    id: "11",
                    titulo: "Navidad en Candy Cane Lane",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BYzYzMGE3YmMtZmE4ZC00YzU5LWE2MDUtYTkyZjljODZhMmYxXkEyXkFqcGdeQXVyMTQ1Njk1OTUw._V1_.jpg',
                    sipnosis: "Un hombre está decidido a ganar el concurso anual de decoración navideña del barrio. Hace un pacto con un elfo para que le ayude a ganar y el elfo lanza un hechizo que da vida a los 12 días de Navidad, provocando el caos en la ciudad.",
                    duracion: "1h 57min",
                    genero: "Comedia",
                    direccion: "Reginald Hudlin",
                    guion: "Reginald Hudlin",
                    puntuacion: 5.6,
                    url: 'https://www.youtube.com/watch?v=WmOeNbvPDiU'
                },
                {
                    id: "12",
                    titulo: "Solo en casa",
                    year: 1990,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BYWE0ZmMzMDEtZmE2ZC00NzMxLTk4NjAtNWZmOTVmNzJkMDg1XkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg',
                    sipnosis: "Un travieso niño de ocho años debe proteger su casa de un par de ladrones cuando accidentalmente su familia lo deja solo en casa durante las vacaciones de Navidad.",
                    duracion: "1h 43min",
                    genero: "Comedia",
                    direccion: "Chris Columbus",
                    guion: "John Hughes",
                    puntuacion: 7.7,
                    url: 'https://www.youtube.com/watch?v=4nXRb-1-n60'
                },
                {
                    id: "13",
                    titulo: "Saltburn: El Laberinto",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BM2NmMDQ1ZWEtNDU4OS00MGIxLWEyMGMtMTM2YmFkYzNhYmMxXkEyXkFqcGdeQXVyMTM1NjM2ODg1._V1_.jpg',
                    sipnosis: "Un estudiante de la Universidad de Oxford se ve envuelto en el mundo de un compañero de clase encantador y aristocrático, que lo invita a la extensa finca de su excéntrica familia para pasar un verano inolvidable.",
                    duracion: "2h 11min",
                    genero: "Comedia",
                    direccion: "Emerald Fennell",
                    guion: "Emerald Fennell",
                    puntuacion: 7.5,
                    url: 'https://www.youtube.com/watch?v=jg7ZSQlgh_Y'
                },
                {
                    id: "14",
                    titulo: "Barbie",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BZjhlOWYyNWMtMzIxZi00MmQxLTk4MTktNWIxZGNmM2NjOWM5XkEyXkFqcGdeQXVyMTQ4NTgxNzYx._V1_.jpg',
                    sipnosis: "Barbie sufre una crisis que la lleva a cuestionarse su mundo y su existencia.",
                    duracion: "1h 54min",
                    genero: "Aventura",
                    direccion: "Greta Gerwig",
                    guion: "Greta Gerwig",
                    puntuacion: 7.0,
                    url: 'https://www.youtube.com/watch?v=SFlGgRaik4c'
                },
                {
                    id: "15",
                    titulo: "Rebel Moon - Parte 1: La niña del fuego",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BMTdmZDNhNjgtMjk4NS00YzQzLTliM2UtMDEzZDY2MDZmMTcwXkEyXkFqcGdeQXVyMTA4MzgzNDM3._V1_.jpg',
                    sipnosis: "Una joven busca guerreros de otros planetas para luchar contra los ejércitos tiránicos que aterrorizan a su pacífica colonia.",
                    duracion: "2h 13min",
                    genero: "Acción",
                    direccion: "Zack Snyder",
                    guion: "Zack Snyder",
                    puntuacion: 6.3,
                    url: 'https://www.youtube.com/watch?v=fk9UKHyKxU8'
                },
                {
                    id: "16",
                    titulo: "Plan en familia",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BZWQzZWFmOWMtODM4Ni00YjYwLWI4ZTYtOTkwZmYyMzFkN2E2XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg',
                    sipnosis: "Un antiguo asesino de alto rango que vive de incógnito como padre de los suburbios debe llevar a su desprevenida familia a la fuga cuando su pasado lo alcanza.",
                    duracion: "1h 58min",
                    genero: "Acción",
                    direccion: "Simon Cellan Jones",
                    guion: "David Coggeshall",
                    puntuacion: 6.3,
                    url: 'https://www.youtube.com/watch?v=oXDrL-fQMn8'
                },
                {
                    id: "17",
                    titulo: "Los que se quedan",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BNDc2MzNkMjMtZDY5NC00NmQ0LWI1NjctZjRhNWIzZjc4MGRiXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg',
                    sipnosis: "La historia de Paul Hunham, un solitario profesor de historia de un instituto de Massachusetts. Sin familia ni amigos, Paul aprovecha las vacaciones para vigilar a los alumnos que no han vuelto a casa.",
                    duracion: "2h 13min",
                    genero: "Comedia",
                    direccion: "Alexander Payne",
                    guion: "David Hemingson",
                    puntuacion: 8.0,
                    url: 'https://www.youtube.com/watch?v=zIy3ixhneCU'
                },
                {
                    id: "18",
                    titulo: "Maestro",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BZjQ4YjdmMjYtZDM1Ny00M2I2LTliMGMtNzUyODk4ZmRmYmQzXkEyXkFqcGdeQXVyMzUxNTM4ODc@._V1_.jpg',
                    sipnosis: "Sigue la compleja historia de amor de Leonard Bernstein y Felicia Montealegre; desde el momento en que se conocieron en 1946 en una fiesta, pasando por dos compromisos, un matrimonio de 25 años y tres hijos.",
                    duracion: "2h 9min",
                    genero: "Biografía",
                    direccion: "Bradley Cooper",
                    guion: "Bradley Cooper",
                    puntuacion: 7.1,
                    url: 'https://www.youtube.com/watch?v=MEXPgGufaQE'
                },
                {
                    id: "19",
                    titulo: "The Iron Claw",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BNTMyNmNlYjItNmM2Yi00YWViLTk5Y2MtNGI4YWEyOWU4N2U2XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg',
                    sipnosis: "La historia real de los inseparables hermanos Von Erich, que hicieron historia en el mundo intensamente competitivo de la lucha libre profesional a principios de la década de 1980.",
                    duracion: "2h 10min",
                    genero: "Biografía",
                    direccion: "Sean Durkin",
                    guion: "Sean Durkin",
                    puntuacion: 8.0,
                    url: 'https://www.youtube.com/watch?v=VfudCfQatwQ'
                },
                {
                    id: "20",
                    titulo: "Leo",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BZDNiZWI3ZmItMjY4OS00Mjk5LThlNjktMmMwZDM1OTEwOGVmXkEyXkFqcGdeQXVyMDc5ODIzMw@@._V1_.jpg',
                    sipnosis: "Adam Sandler da voz al lagarto Leo en la versión original de esta comedia musical sobre un último curso muy especial visto a través de los ojos de la mascota del colegio.",
                    duracion: "1h 42min",
                    genero: "Animación",
                    direccion: "Robert Marianetti",
                    guion: "Robert Smigel",
                    puntuacion: 7.0,
                    url: 'https://www.youtube.com/watch?v=cGObQihdGxU'
                },
                {
                    id: "21",
                    titulo: "Super Mario Bros.: La película",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BZDY2Y2ZhZjctN2ZkNC00NzU3LWI4OGEtMTlkMGNlOGExNTNiXkEyXkFqcGdeQXVyMTU3NDg0OTgx._V1_.jpg',
                    sipnosis: "Un fontanero llamado Mario viaja a través de un laberinto subterráneo con su hermano, Luigi, tratando de salvar a una princesa capturada.",
                    duracion: "1h 32min",
                    genero: "Animación",
                    direccion: "Aaron Horvath",
                    guion: "Matthew Fogel",
                    puntuacion: 7.0,
                    url: 'https://www.youtube.com/watch?v=_1f2RLdxQfA'
                },
                {
                    id: "22",
                    titulo: "Anatomía de una caída",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BYTIwNWU3NzgtYmEyOS00NzEwLTgwYWItNTBlMDdiMDZmZDEwXkEyXkFqcGdeQXVyMTYzMDUzNjEw._V1_.jpg',
                    sipnosis: "Una mujer es sospechosa del asesinato de su marido, y el hijo ciego de ambos se enfrenta a un dilema moral como único testigo.",
                    duracion: "2h 31min",
                    genero: "Crimen",
                    direccion: "Justine Triet",
                    guion: "Justine Triet",
                    puntuacion: 7.9,
                    url: 'https://www.youtube.com/watch?v=KCdtwKRn3J0'
                },
                {
                    id: "23",
                    titulo: "Misterio en Venecia",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BOThjZWRkMTktNGNhNS00MzJlLWFiNjgtOWZkOTJiZmVhMWJlXkEyXkFqcGdeQXVyMzUxNTM4ODc@._V1_.jpg',
                    sipnosis: "En la Venecia posterior a la Segunda Guerra Mundial, Poirot, retirado y viviendo en su propio exilio, asiste a regañadientes a una sesión de espiritismo. Cuando uno de los invitados es asesinado, depende del detective descubrir al asesino.",
                    duracion: "1h 43min",
                    genero: "Crimen",
                    direccion: "Kenneth Branagh",
                    guion: "Michael Green",
                    puntuacion: 6.5,
                    url: 'https://www.youtube.com/watch?v=DNkbSr9Kir4'
                },
                {
                    id: "24",
                    titulo: "Wish: El poder de los deseos",
                    year: 2023,
                    imagen: 'https://m.media-amazon.com/images/M/MV5BODEzNDk4OTktNzlmZC00ZmFhLWJjMTUtODc3NTFiMTUwYmY5XkEyXkFqcGdeQXVyMzUxNTM4ODc@._V1_.jpg',
                    sipnosis: "Asha, una optimista con mucho ingenio, pide un deseo tan potente que le responde una fuerza cósmica, una pequeña bola de energía ilimitada llamada Estrella. Juntas, Asha y Estrella se enfrentan a un imponente enemigo, el Rey Magnífico.",
                    duracion: "1h 35min",
                    genero: "Animación",
                    direccion: "Chris Buck",
                    guion: "Jennifer Lee",
                    puntuacion: 5.8,
                    url: 'https://www.youtube.com/watch?v=CdDxYZkCj6c'
                },
                ]);
            }, 1500);
    }, []);

    return movies;
}